server:
  port: 8181
  servlet:
    context-path: /food_delivery



spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
